version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"      # Redirect HTTP traffic to port 80
      - "443:443"      # HTTPS traffic on 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always
