name: Deploy to Server

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Start SSH Agent and Load Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan -H 139.59.161.146 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh root@139.59.161.146 << 'EOF'
          cd /root/student-affairs-site  # Change to project directory
          git pull origin main  # Pull latest code
          docker-compose down  # Stop running containers
          docker-compose build  # Build a new image from the latest code
          docker-compose up -d  # Run the updated container in the background
          docker image prune -f  # Clean up old images
        EOF
